[profile.default]
src = "contracts"
out = "out"
libs = ["node_modules", "lib"]
remappings = [
    "@openzeppelin/=node_modules/@openzeppelin/",
    "@ethereum-attestation-service/=node_modules/@ethereum-attestation-service/",
    "forge-std/=lib/forge-std/src/"
]

# See more config options at: https://book.getfoundry.sh/config/

[rpc_endpoints]
base_sepolia = "${RPC_URL}"

[etherscan]
base_sepolia = { key = "${BASESCAN_API_KEY}" }
